apiVersion: v1
kind: Service
metadata:
  name: cannabis-api-db
  namespace: default
spec:
  selector:
    app: cannabis-api-db
  ports:
    - name: cannabis-api-db
      port: 5432
      targetPort: 5432
